#!/usr/bin/env python3
# arginfo.py -- php's own parameter declarations for the builtins mc-php has.
#
#     python3 tests/arginfo.py           writes src/arginfo.mc
#     python3 tests/arginfo.py --check   exits 1 when src/arginfo.mc is stale
#
# A builtin given the wrong argument type is php's ZPP: a TypeError, a
# deprecation (null to a non-nullable scalar, a float that loses precision),
# or a coercion. What it says names the parameter -- `Argument #2 ($times)
# must be of type int` -- so the compiler needs every parameter's name and
# type, and php-src's *.stub.php files are where php itself declares them.
# The names are the builtins src/builtin.mc dispatches on and the library rows
# src/decl.mc registers; a name with no stub (mcphp_*) gets no row.
#
# Only the types ZPP coerces between are kept -- string, int, float, bool,
# array and their unions, nullable or not -- with the stub's own spelling,
# which is what php prints. A callback is kept as `callable` (src/builtin.mc
# reads it for the builtin's frame). Any other parameter (mixed, object, a
# class, a by-reference one) is written as `-`: the compiler checks nothing
# there.
import os
import re
import sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_path = os.path.join(root, "src", "arginfo.mc")

names = set()
for f in ("builtin.mc",):
    for m in re.finditer(r'str_eq\(name, "([a-z_0-9]+)"\)', open(os.path.join(root, "src", f)).read()):
        names.add(m.group(1))
for f in os.listdir(os.path.join(root, "src")):
    if f.endswith(".mc"):
        for m in re.finditer(r'ph_lib\("([a-z_0-9]+)"', open(os.path.join(root, "src", f)).read()):
            names.add(m.group(1))

if not os.path.isdir(os.path.join(root, "php-src", "ext")):
    sys.exit("arginfo.py: no php-src/ beside the sources (git clone php-src at php-8.5.10)")
stubs = {}
for d, _, fs in [w for top in ("ext", "Zend") for w in os.walk(os.path.join(root, "php-src", top))]:
    for f in fs:
        if not f.endswith(".stub.php"):
            continue
        src = open(os.path.join(d, f)).read()
        src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
        src = re.sub(r"#\[[^\]]*\]", "", src)
        # top-level functions only: a method is indented inside a class
        for m in re.finditer(r"^function\s+([a-z_0-9]+)\s*\((.*?)\)\s*(?::|\{)", src, flags=re.S | re.M):
            stubs.setdefault(m.group(1), m.group(2))

KEEP = {"string", "int", "float", "bool", "array", "null"}


def param(p):
    p = p.strip()
    p = p.split("=")[0].strip()
    m = re.match(r"^(.*?)\s*(&)?\s*(\.\.\.)?\$([a-zA-Z_0-9]+)$", p)
    if not m:
        return None
    ty, ref, var, nm = m.group(1).strip(), m.group(2), m.group(3), m.group(4)
    if var:
        nm = ""                       # php names no variadic argument
    if ref or not ty:
        return ("-", nm, var)
    # a callback: ZPP checks nothing here, but the compiler needs to know --
    # php calls it from INSIDE the builtin, whose frame the trace then shows
    if ty in ("callable", "?callable"):
        return (ty, nm, var)
    parts = ty[1:].split("|") + ["null"] if ty.startswith("?") else ty.split("|")
    # a class in a union (count's Countable|array) accepts an object, of any
    # class: the runtime that receives it is the one that tells them apart
    if any(t[:1].isupper() for t in parts) and any(t in KEEP for t in parts):
        parts = [t for t in parts]
    elif not all(t in KEEP for t in parts) or parts == ["null"]:
        return ("-", nm, var)
    return (ty, nm, var)


def split_params(s):
    out, depth, cur, q = [], 0, "", ""
    for c in s:
        if q:
            cur += c
            if c == q:
                q = ""
            continue
        if c in "'\"":
            q = c
            cur += c
            continue
        if c in "([":
            depth += 1
        if c in ")]":
            depth -= 1
        if c == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += c
    if cur.strip():
        out.append(cur)
    return out


rows = []
for n in sorted(names):
    if n not in stubs:
        continue
    ps = [param(p) for p in split_params(stubs[n])]
    if any(p is None for p in ps):
        sys.exit("arginfo.py: cannot read the stub of %s" % n)
    if all(p[0] == "-" for p in ps):
        continue
    enc = ";".join("%s%s:%s" % ("*" if v else "", t, nm) for t, nm, v in ps)
    rows.append((n, enc))

text = """// arginfo.mc -- GENERATED by tests/arginfo.py from php-src's *.stub.php; do
// not edit. One row per builtin mc-php has whose parameters ZPP checks: the
// parameters in order, each `TYPE:NAME` with php's own spelling of the type,
// `-` for one nothing is checked on, `*` before the variadic one (whose
// arguments php names by number only).

uptr ph_arginfo(uptr n) {
"""
for n, enc in rows:
    text += '    if (str_eq(n, "%s")) return "%s";\n' % (n, enc)
text += "    return 0;\n}\n"

# every builtin mc-php has, as php-src declares its arity: "MIN:MAX", MAX -1
# when the last parameter is variadic. A spread into a builtin is dispatched
# on its runtime count against these (src/builtin.mc ph_spread_call).
counts = []
for n in sorted(names):
    if n not in stubs:
        continue
    ps = split_params(stubs[n])
    mn = 0
    mx = len(ps)
    for i, p in enumerate(ps):
        if "..." in p.split("$")[0]:
            mx = -1
            break
        if "=" not in p:
            mn = i + 1
    counts.append((n, mn, mx))
text += """
// php's own arity of every builtin mc-php has: "MIN:MAX", MAX -1 for a
// variadic one
uptr ph_argn(uptr n) {
"""
for n, mn, mx in counts:
    text += '    if (str_eq(n, "%s")) return "%d:%d";\n' % (n, mn, mx)
text += "    return 0;\n}\n"

if "--check" in sys.argv:
    have = open(out_path).read() if os.path.exists(out_path) else ""
    if have != text:
        print("  FAIL  src/arginfo.mc is stale: run python3 tests/arginfo.py")
        sys.exit(1)
    print("  arginfo: %d rows, src/arginfo.mc matches php-src's stubs" % len(rows))
    sys.exit(0)
open(out_path, "w").write(text)
print("arginfo.py: %d rows -> src/arginfo.mc" % len(rows))
