<?php
$cases = [
  ['strrpos("hello world","o")', strrpos("hello world","o")],
  ['strrpos("hello","o",-2)', strrpos("hello","o",-2)],
  ['strrpos("hello world","o",5)', strrpos("hello world","o",5)],
  ['strrpos("hello world","o",-5)', strrpos("hello world","o",-5)],
  ['strrpos("abcabc","",3)', strrpos("abcabc","",3)],
  ['strripos("HeLLo","L")', strripos("HeLLo","L")],
  ['strripos("Hello World","O",-3)', strripos("Hello World","O",-3)],
  ['str_split("abcde",2)', str_split("abcde",2)],
  ['str_split("",1)', str_split("",1)],
  ['chunk_split("abcdefg",3,"|")', chunk_split("abcdefg",3,"|")],
  ['chunk_split("abc",5)', chunk_split("abc",5)],
  ['strspn("42 apples","1234567890")', strspn("42 apples","1234567890")],
  ['strspn("abcd","ab",1,2)', strspn("abcd","ab",1,2)],
  ['strcspn("abcd","c")', strcspn("abcd","c")],
  ['wordwrap("The quick brown fox",10,"\n",true)', wordwrap("The quick brown fox",10,"\n",true)],
  ['wordwrap("A very long woooooooooooord.",8,"\n",true)', wordwrap("A very long woooooooooooord.",8,"\n",true)],
  ['trim(" \0x\t\n ")', trim(" \0x\t\n ")],
  ['trim("xxhixx","x")', trim("xxhixx","x")],
  ['trim("a..z","a..z")', trim("a..z","a..z")],
  ['ltrim("  hi")', ltrim("  hi")],
  ['rtrim("hi..","." )', rtrim("hi..",".")],
  ['strtr("hi","ih","HI")', strtr("hi","ih","HI")],
  ['strtr("hi all",["hi"=>"bye","all"=>"you"])', strtr("hi all",["hi"=>"bye","all"=>"you"])],
  ['substr_replace("Hello","X",1,2)', substr_replace("Hello","X",1,2)],
  ['strrchr("a/b/c","/")', strrchr("a/b/c","/")],
  ['stripslashes("a\\\\\'b")', stripslashes("a\\\'b")],
  ['strncasecmp("Hello","HELLO",5)', strncasecmp("Hello","HELLO",5)],
];
foreach ($cases as $c) { echo $c[0], " => ", var_export($c[1], true), "\n"; }
